spring.application.name=login
logging.level.org.hibernate=ERROR
logging.level.root=ERROR
management.endpoints.web.exposure.include=refresh
spring.config.import=optional:configserver:http://localhost:8888/
spring.application.name=application
app.name=${app.name}