spring.application.name=login
logging.level.org.hibernate=ERROR
logging.level.root=ERROR
management.endpoints.web.exposure.include=refresh
spring.config.import=optional:configserver:http://localhost:8888/
spring.application.name=application
app.name=${app.name}
spring.application.name=spring-project
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/